services:
  postgres:
    image: 'postgres:latest'
    container_name: planejamais_postgres
    restart: no
    environment:
      - 'POSTGRES_DB=planejamais_db'
      - 'POSTGRES_PASSWORD=planeja_pass'
      - 'POSTGRES_USER=planeja_user'
    ports:
      - "5432:5432"